export enum ECommandReturnOptions {
  clear = "clear",
  about = "about",
  showhelp = "show help",
  login = "login",
  logout = "logout",
  error = "error",
  signup = "signup",
  addnewtaskname = "add new task name",
  addnewtask = "add new task",
  showtasknames = "show task names",
  deletetaskname = "delete task name",
  deletetask = "delete task",
  showtasks = "show tasks",
  showtasksfor = "show tasks for",
  showtasksfrom = "show tasks from",
  deletetasksfrom = "delete tasks from",
  deletetasks = "delete tasks for",
}
