export enum ECommandReturnOptions {
  clear = "clear",
  about = "about",
  showhelp = "show help",
  login = "login",
  logout = "logout",
  error = "error",
  signup = "signup",
  addNewTaskName = "add new task name",
  addNewTask = "add new task",
  showTaskNames = "show task names",
  deleteTaskNames = "delete task name",
  deleteTask = "delete task",
  showTasks = "show tasks",
  showTasksFor = "show tasks for",
  showTasksFrom = "show tasks from",
  deleteTasksFrom = "delete tasks from",
  deleteTasksFor = "delete tasks for",
  setBackgroundColor = "set background color",
  setBorderColor = "set border color",
  setShadowColor = "set shadow color",
  setTextColor = "set text color",
  setTerminalColor = "set terminal color",
  setThemeLight = "set theme light",
  setThemeDark = "set theme dark",
}
